version: '3'
services:
  backend:
    build:
      context: ./express
      dockerfile: Dockerfile.backend
    env_file:
      - ./express/.env
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./bluemed
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    restart: always
